services:
  postgres:
    image: postgres:16
    container_name: ticketflow-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ticketflow_postgres_data:/var/lib/postgresql/data
    networks:
      - ticketflow-network
  spring-boot:
    build : .
    container_name: ticket-flow-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - ticketflow-network

volumes:
  ticketflow_postgres_data:

networks:
  ticketflow-network:
    driver: bridge
