name : Ticket flow backend pipeline

on:
  push:
    branches: [main]

jobs:
  compile :
    runs-on: ubuntu-latest
    name: Compile Project
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with :
          java-version: 21
          distribution: "corretto"

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Compile
        run: |
          cd backend/ticketflow
          mvn clean compile


  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "corretto"
      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Run the tests
        run: |
          cd backend/ticketflow
          mvn clean test

  build-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username : ${{ secrets.DOCKERHUB_USERNAME }}
          password : ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Build Image
        uses : docker/build-push-action@v5
        with :
          context : backend/ticketflow
          file : backend/ticketflow/Dockerfile
          push: false
          load: true
          tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/ticketflow:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/ticketflow:sha-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
            

      - name: Scan Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/ticketflow:latest
          format: table
          exit-code: 1
          severity: CRITICAL
          ignore-unfixed: true

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          context: backend/ticketflow
          file: backend/ticketflow/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ticketflow:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ticketflow:sha-${{ github.sha }}
          cache-from: type=gha






